package AppConstants;

/**
 * Created by Okuhle on 7/2/2016.
 */
public enum ExecutionMode {

    EXECUTE_FORGOT_PASSWORD,
    EXECUTE_LOGIN,
    EXECUTE_REGISTER,
    EXECUTE_SEARCH,
    EXECUTE_GET_ATHLETE_ACTIVITY,
    GET_ATHLETE_SUMMARY,
    EXECUTE_GET_ATHLETE_PROFILE,
    EXECUTE_UPDATE_ATHLETE_PROFILE,

}
